Sys.setenv(LANG = "es")
Sys.setenv(LC_COLLATE="es_ES.UTF-8")
Sys.setenv(LC_CTYPE="es_ES.UTF-8")
Sys.setenv(LC_MESSAGES="es_ES.UTF-8")
Sys.setenv(LC_MONETARY="es_ES.UTF-8")
Sys.setenv(LC_NUMERIC="es_ES.UTF-8")
Sys.setenv(LC_TIME="es_ES.UTF-8")
Sys.setenv(LC_ALL="es_ES.UTF-8")
invisible(Sys.setlocale(category = "LC_ALL", locale = "es_ES.UTF-8"))
invisible(Sys.setlocale(category = "LC_MESSAGES", locale = "es_ES.UTF-8"))
