---
title: "Introducción a la Ciencia de Datos"
subtitle: "Análisis de datos y algoritmos de predicción con R"
author: "Rafael A. Irizarry"
date: "`r Sys.Date()`"
documentclass: krantz
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
colorlinks: yes
lot: no
lof: no
graphics: yes
urlcolor: blue
geometry: "left=1.5in, right=1.5in, top=1.25in, bottom=1.25in"
description: Este libro presenta conceptos y destrezas que les ayudarán abordar los retos de situaciones actuales del análisis de datos. Cubre conceptos de probabilidad, inferencia estadística, regresión lineal y machine learning.  Además, les permitirá desarrollar destrezas como la programación R, el wrangling de datos con dplyr, la visualización de datos con ggplot2, la organización de archivos con Shell de UNIX / Linux, el control de versiones con GitHub y la preparación de documentos reproducibles con R markdown.
#documentclass: book
#classoption: openany
site: bookdown::bookdown_site
always_allow_html: yes
---


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
.packages(), 'bookdown', 'knitr', 'rmarkdown'), 'packages.bib')
```

# Prefacio{-}

Este libro comenzó como las notas utilizadas para enseñar la clase de
HarvardX [Data Science Series](https://www.edx.org/professional-certificate/harvardx-data-science)^[https://www.edx.org/professional-certificate/harvardx-data-science].

El código Rmarkdown que se usó para generar el libro está disponible en [GitHub](https://github.com/rafalab/dsbook)^[https://github.com/rafalab/dsbook]. Tengan en cuenta que el tema gráfico utilizado para los gráficos a lo largo del libro se pueden recrear utilizando la función `ds_theme_set()` del paquete __dslabs__.

Un PDF de la versión en inglés de este libro está disponible en [Leanpub](https://leanpub.com/datasciencebook)^[https://leanpub.com/datasciencebook].

Una copia impresa de la versión en inglés de este libro está disponible en [CRC Press](https://www.crcpress.com/Introduction-to-Data-Science-Data-Analysis-and-Prediction-Algorithms-with/Irizarry/p/book/9780367357986)^[ https://www.crcpress.com/Introduction-to-Data-Science-Data-Analysis-and-Prediction-Algorithms-with/Irizarry/p/book/9780367357986].

Este trabajo se publica bajo la licencia Creative Commons Attribution-NonCommercial-ShareAlike 4.0 Internacional [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).

Hacemos anuncios relacionados al libro en Twitter. Para la información más reciente, siga [\@rafalab](https://twitter.com/rafalab).

# Agradecimientos {-}

Este libro está dedicado a todas las personas involucradas en la construcción y el mantenimiento de R y los paquetes R que utilizamos en el texto. Un agradecimiento especial a los desarrolladores y los mantenedores de base R, el _tidyverse_ y el paquete __caret__.

Un agradecimiento especial a mi _tidyverse_ gurú David Robinson y a Amy Gill por docenas de comentarios, cambios y sugerencias. Además, muchas gracias a Stephanie Hicks, que dos veces sirvió como co-instructora en mis clases de ciencias de datos, y a Yihui Xie, que pacientemente toleró mis multiples preguntas sobre bookdown. Gracias también a Karl Broman, de quien tomé prestadas ideas para las secciones sobre la visualización de datos y las herramientas de productividad, y a Hector Corrada-Bravo, por sus consejos sobre cómo mejor enseñar _machine learning_. Gracias a Peter Aldhous, de quien tomé prestadas ideas para la sección sobre los principios de la visualización de datos y a Jenny Bryan por escribir _Happy Git_ y _GitHub for the useR_, que influyeron en nuestros capítulos de Git. Gracias a Alyssa Frazee por ayudar a crear el problema de tarea que se convirtió en el capítulo sobre los sistemas de recomendación y a Amanda Cox por proporcionar los datos de los exámenes de los Regentes de Nueva York. Además, muchas gracias a Jeff Leek, Roger Peng y Brian Caffo, cuya clase inspiró la forma en que se divide este libro y a Garrett Grolemund y Hadley Wickham por abrir el código de reserva para su libro R for Data Science. Finalmente, gracias a Alex Nones por corregir el manuscrito durante sus diversas etapas.

Este libro fue concebido durante la enseñanza de varios cursos de estadística aplicada, comenzando hace más de quince años. Los profesores asistentes que trabajaron conmigo a lo largo de los años hicieron importantes contribuciones indirectas a este libro. La última versión de este curso es una serie de HarvardX coordinada por Heather Sternshein y Zofia Gajdos. Les agradecemos sus contribuciones. También estamos agradecidos a todos los estudiantes cuyas preguntas y comentarios nos ayudaron a mejorar el libro. Los cursos fueron parcialmente financiados por el subsidio del NIH R25GM114818. Agradecemos los Institutos Nacionales de Salud por su apoyo.

Un agradecimiento especial a todos aquellos que editaron el libro a través de _pull requests_ de GitHub o hicieron sugerencias creando un _issue_ o enviando un correo electrónico: `nickyfoto` (Huang Qiang) `desautm` (Marc-André Désautels), `michaschwab` (Michail Schwab) `alvarolarreategui` (Alvaro Larreategui), `jakevc` (Jake VanCampen), `omerta` (Guillermo Lengemann), `espinielli` (Enrico Spinielli), `asimumba`(Aaron Simumba) `braunschweig` (Maldewar), `gwierzchowski` (Grzegorz Wierzchowski), `technocrat` (Richard Careaga) `atzakas`, `defeit` (David Emerson Feit), `shiraamitchell` (Shira Mitchell) `Nathalie-S`, `andreashandel` (Andreas Handel) `berkowitze` (Elias Berkowitz) `Dean-Webb` (Dean Webber), `mohayusuf`, `jimrothstein`, `mPloenzke` (Matthew Ploenzke), `NicholasDowand` (Nicholas Dow) `kant` (Darío Hereñú), `debbieyuster` (Debbie Yuster), `tuanchauict` (Tuan Chau), `phzeller`, David D. Kane, El Mustapha El Abbassi y Vadim Zipunnikov.


La traducción del libro al español estuvo a cargo de Alex Nones. Agradecemos a todos los que contribuyeron a esta traducción.  Ilia Ushkin and Dustin Tingley generaron un primer borrador usando un programa de traducción automática. A través de Twitter \@R4DS_es y \@_lacion_ (Laura Ación) proveyeron importante información sobre recursos existentes. Varios otros contribuyeron a traves de Twitter, GitHub, o email: \@hortizzuazaga (Humberto Ortiz), \@ribnikov (Jose Matestadístico),  \@jarangoo (Julián A.), \@DiegoV_O_
(Diego), \@BrunoContrerasM (BContreras Moreira), \@a2kimura (Alejandro Kimura), \@Emilio_NTN (Emilio García Morán), \@beto_bfr (betofogo), \@jdieramon (Jose V. Die), \@yabellini (Yanina Bellini Saibene),  \@symusicgroup (Ismael Rudas), \@criztinaz (Cristina Zenteno), \@controlnegativo (Cristina de Dios), \@d_olivaw (Elio Campitelli), \@aguerri_jc (Jesús C. Aguerri), \@pincheippie (Francisco, en casa) \@compBiology (Pedro Madrigal), \@RLadiesCuerna (RLadies Cuernavaca), \@thecarpentries, `eead-csic-compbio` (CSIC & Fundación ARAID), `pablormier` (Pablo R. Mier), `josschavezf` (Joselyn Chavez), `jmcastagnetto` (Jesus M. Castagnetto), `ismaelrudas`, `AnaBVA` (Ana B. Villaseñor Altamirano), Héctor Corrada-Bravo, Rafael A. Arce Nazario, Luis R. Pericchi Guerra, y Maria E. Perez Hernandez.





