# Probabilidad

En los juegos de azar, la probabilidad tiene una definición muy intuitiva. Por ejemplo, sabemos lo que significa cuando decimos que la probabilidad de que un par de dados salga siete es 1 en 6. Sin embargo, este no es el caso en otros contextos. Hoy la teoría de la probabilidad se está utilizando de manera mucho más amplia con la palabra _probabilidad_ comúnmente utilizada en el lenguaje cotidiano. [fix] Si escribimos "¿Cuáles son las posibilidades de" en Google, su función de autocompletar nos da: "tener gemelos", "llover hoy", "ser alcanzado por un rayo" y "contraer cáncer". Uno de los objetivos de esta parte del libro es ayudarnos a comprender cómo la probabilidad es útil para entender y describir eventos del mundo real cuando realizamos análisis de datos.

Dado que saber cómo calcular las probabilidades nos da una ventaja en los juegos de azar, a lo largo de la historia muchas personas inteligentes, incluyendo matemáticos famosos como Cardano, Fermat y Pascal, le han dedicado tiempo y energía a pensar en las matemáticas de estos juegos. Como resultado, nació la teoría de la probabilidad. La probabilidad sigue siendo muy útil en los juegos de azar modernos. [fix] Por ejemplo, en el póker, podemos calcular la probabilidad de ganar una mano basados en las cartas en la mesa. Además, los casinos se basan en la teoría de la probabilidad para desarrollar juegos que casi con certeza garantizan ganancias.

La teoría de la probabilidad es útil en muchos otros contextos y, en particular, en áreas que de alguna manera dependen de los datos afectados por el azar. Todos los otros capítulos de esta parte se basan en la teoría de la probabilidad. El conocimiento de la probabilidad es, por lo tanto, indispensable para la ciencia de datos.

