# (PART) Estadísticas con R {-}

# Introducción a las estadísticas con R

El análisis de datos es uno de los enfoques principales de este libro. Si bien las herramientas informáticas que hemos introducido son desarrollos relativamente recientes, el análisis de datos ha existido durante más de un siglo. A lo largo de los años, los analistas de datos que trabajan en proyectos específicos han presentado ideas y conceptos que se generalizan a muchas otras aplicaciones. También han identificado maneras comunes en que patrones aparentes en los datos y realidades matemáticas importantes que no son inmediatamente obvias nos pueden engañar. La acumulación de estas ideas y perspectivas ha dado lugar a la disciplina de la estadística, que proporciona un marco matemático que facilita enormemente la descripción y la evaluación formal de estas ideas.

Para evitar repetir errores comunes y perder el tiempo reinventando la rueda, es importante que un analista de datos tenga una comprensión profunda de las estadísticas. Debido a la madurez de la disciplina, hay docenas de libros excelentes ya publicados sobre este tema y, por lo tanto, no nos enfocaremos en describir el marco matemático aquí. En cambio, presentamos conceptos brevemente y luego proporcionamos estudios de caso detallados que demuestran cómo se utilizan las estadísticas en el análisis de datos junto con el código R que implementa estas ideas. También usamos el código R para ayudar a aclarar algunos de los principales conceptos estadísticos que generalmente se describen usando las matemáticas. Recomendamos altamente complementar esta parte del libro con un libro de texto de estadísticas básicas. Dos ejemplos son _Statistics_ de Freedman, Pisani y Purves y _Statistical Inference_ de Casella y Berger. Los conceptos específicos cubiertos en esta parte del libro son Probabilidad, Inferencia estadística, Modelos estadísticos, Regresión y Modelos lineales, que son los principales temas cubiertos en un curso de estadística. Los estudios de caso que presentamos se relacionan con la crisis financiera, el pronóstico de los resultados de las elecciones, cómo entender la herencia y cómo formar un equipo de béisbol.

