# (PART) _Wrangling_ de datos {-}


# Introducción al wrangling de datos

Los sets de datos utilizados en este libro se han puesto a su disposición como objetos R, específicamente como _data frames_. Los datos de asesinatos de EE. UU., los datos reportados de alturas y los datos de Gapminder son todos _data frames_. Estos sets de datos vienen incluidos en el paquete __dslabs__ y los cargamos usando la función `data`. Además, hemos puesto a disposición los datos en formato `tidy`. Los paquetes y las funciones de tidyverse suponen que los datos son `tidy` y esta suposición es una gran parte de la razón por la que estos paquetes funcionan tan bien juntos.

Sin embargo, es bien raro que en un proyecto de ciencia de datos haya datos fácilmente disponibles como parte de un paquete. Hicimos un buen trabajo "tras bastidores" para convertir los datos originales en las tablas _tidy_ con que trabajamos. Mucho más común es que los datos estén en un archivo, una base de datos o extraídos de un documento, incluyendo páginas web, tuits o PDF. En estos casos, el primer paso es importar los datos a R y, cuando estemos usando __tidyverse__, ordenar los datos. Este paso inicial en el proceso de análisis de datos generalmente implica varios pasos, a menudo complicados, para convertir datos al formato _tidy_ que facilita enormemente el resto del análisis. Nos referimos a este proceso como _wrangling de datos_.

Aquí cubrimos varios pasos comunes del proceso del _wrangling_ de datos, incluyendo cómo convertir los datos en formato _tidy_, procesar cadenas, leer y procesar (_parse_ en inglés) html, trabajar con fechas y horas y _mineria de textos_ (_text mining_ en inglés). Raras veces se necesita hacer todos estos pasos de _wrangling_ en un solo análisis, pero los científicos de datos probablemente los enfrentarán a todos en algún momento. Algunos de los ejemplos que utilizamos para demostrar las técnicas del _wrangling_ de datos se basan en el trabajo que hicimos para convertir datos crudos en los sets de datos _tidy_ ofrecidos por el paquete __dslabs__ y utilizados en el libro como ejemplos.


